/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.cse.cse564.CRUD;

import javax.ws.rs.core.MediaType;
import javax.ws.rs.core.MultivaluedMap;
import javax.ws.rs.core.Response;

import com.sun.jersey.api.client.Client;
import com.sun.jersey.api.client.ClientResponse;
import com.sun.jersey.api.client.UniformInterfaceException;
import com.sun.jersey.api.client.WebResource;
import com.sun.jersey.api.client.config.ClientConfig;
import com.sun.jersey.api.client.config.DefaultClientConfig;
import com.sun.jersey.api.representation.Form;
import com.sun.jersey.core.util.MultivaluedMapImpl;

/**
 *
 * @author acheruvu
 */
public class ClientUI extends javax.swing.JFrame {

    private WebResource webResource;
    private Client client;
    private static final String BASE_URI = "http://localhost:8080/CRUD_serve";
    public int radionum;

    /**
     * Creates new form temp
     */
    public ClientUI() {
        initComponents();
        ClientConfig config = new DefaultClientConfig();
        client = Client.create(config);
        webResource = client.resource(BASE_URI).path("/");
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        createRadioButton = new javax.swing.JRadioButton();
        readRadioButton = new javax.swing.JRadioButton();
        putRadioButton = new javax.swing.JRadioButton();
        deleteRadioButton = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        studentidTextField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        studentnameTextField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        gradeidTextField = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        gradeTextField = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        percentageTextField = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        feedbackTextField = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        responsecodeTextField = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        methodTextField = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        locationTextField = new javax.swing.JTextField();
        submitButton = new javax.swing.JButton();
        gradebookbutton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        createRadioButton.setText("CREATE");
        createRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createRadioButtonActionPerformed(evt);
            }
        });

        readRadioButton.setText("READ");
        readRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                readRadioButtonActionPerformed(evt);
            }
        });

        putRadioButton.setText("PUT");
        putRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                putRadioButtonActionPerformed(evt);
            }
        });

        deleteRadioButton.setText("DELETE");
        deleteRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteRadioButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(deleteRadioButton)
                    .addComponent(putRadioButton)
                    .addComponent(readRadioButton)
                    .addComponent(createRadioButton))
                .addContainerGap(56, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(createRadioButton)
                .addGap(18, 18, 18)
                .addComponent(readRadioButton)
                .addGap(18, 18, 18)
                .addComponent(putRadioButton)
                .addGap(18, 18, 18)
                .addComponent(deleteRadioButton)
                .addContainerGap(101, Short.MAX_VALUE))
        );

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        jLabel1.setText("                       GRADEBOOK");

        jLabel2.setText("Student ID");

        studentidTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                studentidTextFieldActionPerformed(evt);
            }
        });

        jLabel3.setText("Student Name");

        studentnameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                studentnameTextFieldActionPerformed(evt);
            }
        });

        jLabel4.setText("Grade ID");

        gradeidTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gradeidTextFieldActionPerformed(evt);
            }
        });

        jLabel5.setText("Grade");

        jLabel6.setText("Percentage");

        jLabel7.setText("Feedback");

        feedbackTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                feedbackTextFieldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(studentnameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))
                        .addGap(8, 8, 8)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(38, 38, 38)
                                .addComponent(gradeidTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(percentageTextField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(gradeTextField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(studentidTextField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(feedbackTextField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(57, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(studentidTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(studentnameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(gradeidTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(gradeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(percentageTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(feedbackTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(64, 64, 64))
        );

        jLabel8.setText("    HTTP INFOMATION");

        jLabel9.setText("HTTP Response Code");

        responsecodeTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                responsecodeTextFieldActionPerformed(evt);
            }
        });

        jLabel10.setText("   Method");

        methodTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                methodTextFieldActionPerformed(evt);
            }
        });

        jLabel11.setText("Location");

        locationTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                locationTextFieldActionPerformed(evt);
            }
        });

        submitButton.setText("SUBMIT");
        submitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitButtonActionPerformed(evt);
            }
        });

        gradebookbutton.setText("Complete Gradebook of Class");
        gradebookbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gradebookbuttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(185, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(58, 58, 58)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(142, 142, 142))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(26, 26, 26)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(responsecodeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(43, 43, 43)
                                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(27, 27, 27)
                                        .addComponent(methodTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(locationTextField)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(55, 55, 55)
                                .addComponent(submitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(37, 37, 37)
                                .addComponent(gradebookbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(182, 182, 182)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 463, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(312, 312, 312))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel8)
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(responsecodeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(methodTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(locationTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(submitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(gradebookbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void createRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createRadioButtonActionPerformed
            // TODO add your handling code here:
            radionum=1;
            putRadioButton.setSelected(false);
            deleteRadioButton.setSelected(false);
            readRadioButton.setSelected(false);
            studentnameTextField.setText("");
            studentidTextField.setText("");
            gradeTextField.setText("");
            gradeidTextField.setText("");
            feedbackTextField.setText("");
            percentageTextField.setText("");
            locationTextField.setText("");
            methodTextField.setText("");
            responsecodeTextField.setText("");
            
            
    }//GEN-LAST:event_createRadioButtonActionPerformed

    private void studentidTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_studentidTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_studentidTextFieldActionPerformed

    private void studentnameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_studentnameTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_studentnameTextFieldActionPerformed

    private void gradeidTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gradeidTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_gradeidTextFieldActionPerformed

    private void feedbackTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_feedbackTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_feedbackTextFieldActionPerformed

    private void responsecodeTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_responsecodeTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_responsecodeTextFieldActionPerformed

    private void methodTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_methodTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_methodTextFieldActionPerformed

    private void locationTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_locationTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_locationTextFieldActionPerformed

    private void submitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitButtonActionPerformed
        // TODO add your handling code here:
        
        String givenstudentid=studentidTextField.getText();
            String givenstudentname=studentnameTextField.getText();
            String grade=gradeTextField.getText();
            String gradeID=gradeidTextField.getText();
            String percentage= percentageTextField.getText();
            String feedback= feedbackTextField.getText();
            ClientApp obj=new ClientApp();
            ClientResponse r;
            String answer;
            String [] tokens;
            String location;
        if (radionum==1)
        {
            
            
            if(!givenstudentid.equalsIgnoreCase("") && !givenstudentname.equals("") && !gradeID.equals("")&& !percentage.equals(""))
            {
                r=obj.createStudent(givenstudentid, givenstudentname);
                answer=r.toString();
                tokens=answer.split(" ");
                System.out.println();
                for(String s:tokens)
                {
                    System.out.println(s);
                }
                location=tokens[1]+"/"+givenstudentid;
                locationTextField.setText(location);
                responsecodeTextField.setText(tokens[7]);
                 String methodvalue="";
                       for(int i=8; i<tokens.length;i++)
                       {
                           methodvalue=methodvalue+" "+tokens[i]+" ";
                       }
                methodTextField.setText(methodvalue);
                
                r=obj.createGradeItem(gradeID, percentage);
                answer=r.toString();
                tokens=answer.split(" ");
                System.out.println();
                for(String s:tokens)
                {
                    System.out.println(s);
                }
               // location=tokens[1]+"/"+givenstudentid;
               // locationTextField.setText(location);
                responsecodeTextField.setText(tokens[7]);
                methodvalue="";
                       for(int i=8; i<tokens.length;i++)
                       {
                           methodvalue=methodvalue+" "+tokens[i]+" ";
                       }
                methodTextField.setText(methodvalue);
                
                
            }
            else if (!givenstudentid.equals("") && !givenstudentname.equals(""))
            {
                r=obj.createStudent(givenstudentid, givenstudentname);
                answer=r.toString();
                tokens=answer.split(" ");
                System.out.println();
                for(String s:tokens)
                {
                    System.out.println(s);
                }
                location=tokens[1]+"/"+givenstudentid;
                locationTextField.setText(location);
                responsecodeTextField.setText(tokens[7]);
                 String methodvalue="";
                       for(int i=8; i<tokens.length;i++)
                       {
                           methodvalue=methodvalue+" "+tokens[i]+" ";
                       }
                methodTextField.setText(methodvalue);
                
            }
            else
            {
                r=obj.createGradeItem(gradeID, percentage);
                answer=r.toString();
                tokens=answer.split(" ");
                System.out.println();
                for(String s:tokens)
                {
                    System.out.println(s);
                }
                location=tokens[1]+"/"+gradeID;
                locationTextField.setText(location);
                responsecodeTextField.setText(tokens[7]);
                String methodvalue="";
                       for(int i=8; i<tokens.length;i++)
                       {
                           methodvalue=methodvalue+" "+tokens[i]+" ";
                       }
                methodTextField.setText(methodvalue);
                
            }
                
        }
        
        else if (radionum==2)
        {
            if(!gradeID.equals(""))
            {
                r=obj.getGradeDetails(gradeID);
                answer=r.toString();
                tokens=answer.split(" ");
                System.out.println();
                for(String s:tokens)
                {
                    System.out.println(s);
                }
                location=tokens[1];
                locationTextField.setText(location);
                responsecodeTextField.setText(tokens[7]);
                 String methodvalue="";
                       for(int i=8; i<tokens.length;i++)
                       {
                           methodvalue=methodvalue+" "+tokens[i]+" ";
                       }
                methodTextField.setText(methodvalue);
                
            }
            else if(!givenstudentid.equals(""))
            {
                r=obj.getStudentDetails(givenstudentid);
                answer=r.toString();
                tokens=answer.split(" ");
                System.out.println();
                for(String s:tokens)
                {
                    System.out.println(s);
                }
                location=tokens[1];
                locationTextField.setText(location);
                responsecodeTextField.setText(tokens[7]);
                 String methodvalue="";
                       for(int i=8; i<tokens.length;i++)
                       {
                           methodvalue=methodvalue+" "+tokens[i]+" ";
                       }
                methodTextField.setText(methodvalue);
                
            }
            else
            {
                locationTextField.setText("Enter either StudentID or GradeID details");
            }
            
            
           
        }
        
        else if (radionum==3)
        {
            System.out.println("Inside put statement-client");
            if(!givenstudentid.equals("")&& !gradeID.equals("") && !grade.equals("") && !feedback.equals(""))
            {
                r=obj.updateGradeforParticularStudent(givenstudentid,gradeID,grade, feedback);
                answer=r.toString();
                tokens=answer.split(" ");
                System.out.println();
                for(String s:tokens)
                {
                    System.out.println(s);
                }
                location=tokens[1]+"/"+givenstudentid;
                locationTextField.setText(location);
                responsecodeTextField.setText(tokens[7]);
                 String methodvalue="";
                       for(int i=8; i<tokens.length;i++)
                       {
                           methodvalue=methodvalue+" "+tokens[i]+" ";
                       }
                methodTextField.setText(methodvalue);
                
            }
            else
            {
                locationTextField.setText("Enter studnet and grade details that are to be updated");
            }
            
        }
        else if (radionum==4)
        {
            System.out.println("coming into delete student method");
            if(!givenstudentid.equals("") && !gradeID.equals(""))
            {
                System.out.println("deleting grade for particular student");
                System.out.println(givenstudentid);
                System.out.println(gradeID);
                r=obj.deleteGradeforParticularStudent(givenstudentid, gradeID);
                answer=r.toString();
                tokens=answer.split(" ");
                System.out.println();
                for(String s:tokens)
                {
                    System.out.println(s);
                }
                location=tokens[1]+"/"+givenstudentid;
                locationTextField.setText(location);
                responsecodeTextField.setText(tokens[7]);
                 String methodvalue="";
                       for(int i=8; i<tokens.length;i++)
                       {
                           methodvalue=methodvalue+" "+tokens[i]+" ";
                       }
                methodTextField.setText(methodvalue);
                
            }
            else if(givenstudentid.equals("") && !gradeID.equals(""))
            {
                r=obj.deleteGradeItemforallStudents(gradeID);
                //r=obj.updateGradeforParticularStudent(givenstudentid,gradeID,grade, feedback);
                answer=r.toString();
                tokens=answer.split(" ");
                System.out.println();
                for(String s:tokens)
                {
                    System.out.println(s);
                }
                location=tokens[1];
                locationTextField.setText(location);
                responsecodeTextField.setText(tokens[7]);
                 String methodvalue="";
                       for(int i=8; i<tokens.length;i++)
                       {
                           methodvalue=methodvalue+" "+tokens[i]+" ";
                       }
                methodTextField.setText(methodvalue);
            }
            else if(!givenstudentid.equals("") && gradeID.equals(""))
            {
                System.out.println("deleting student");
                r=obj.deleteStudent(givenstudentid);
              //  r=obj.updateGradeforParticularStudent(givenstudentid,gradeID,grade, feedback);
                answer=r.toString();
                tokens=answer.split(" ");
                System.out.println();
                for(String s:tokens)
                {
                    System.out.println(s);
                }
                location=tokens[1];
                locationTextField.setText(location);
                responsecodeTextField.setText(tokens[7]);
                 String methodvalue="";
                       for(int i=8; i<tokens.length;i++)
                       {
                           methodvalue=methodvalue+" "+tokens[i]+" ";
                       }
                methodTextField.setText(methodvalue);
            }
            else
            {
               locationTextField.setText("Enter Location details to delete"); 
            }
        }
    }//GEN-LAST:event_submitButtonActionPerformed

    private void readRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_readRadioButtonActionPerformed
        // TODO add your handling code here:
        radionum=2;
        putRadioButton.setSelected(false);
        deleteRadioButton.setSelected(false);
        createRadioButton.setSelected(false);
        studentnameTextField.setText("");
        studentidTextField.setText("");
        gradeTextField.setText("");
        gradeidTextField.setText("");
        feedbackTextField.setText("");
        percentageTextField.setText("");
        locationTextField.setText("");
        methodTextField.setText("");
        responsecodeTextField.setText("");
               
    }//GEN-LAST:event_readRadioButtonActionPerformed

    private void putRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_putRadioButtonActionPerformed
        // TODO add your handling code here:
        radionum=3;
        createRadioButton.setSelected(false);
        deleteRadioButton.setSelected(false);
        readRadioButton.setSelected(false);
        studentnameTextField.setText("");
        studentidTextField.setText("");
        gradeTextField.setText("");
        gradeidTextField.setText("");
        feedbackTextField.setText("");
        percentageTextField.setText("");
        locationTextField.setText("");
        methodTextField.setText("");
        responsecodeTextField.setText("");
    }//GEN-LAST:event_putRadioButtonActionPerformed

    private void deleteRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteRadioButtonActionPerformed
        // TODO add your handling code here:
        radionum=4;
        putRadioButton.setSelected(false);
        createRadioButton.setSelected(false);
        readRadioButton.setSelected(false);
        studentnameTextField.setText("");
        studentidTextField.setText("");
        gradeTextField.setText("");
        gradeidTextField.setText("");
        feedbackTextField.setText("");
        percentageTextField.setText("");
        locationTextField.setText("");
        methodTextField.setText("");
        responsecodeTextField.setText("");
        
    }//GEN-LAST:event_deleteRadioButtonActionPerformed

    private void gradebookbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gradebookbuttonActionPerformed
        // TODO add your handling code here:
        putRadioButton.setSelected(false);
        createRadioButton.setSelected(false);
        readRadioButton.setSelected(false);
        studentnameTextField.setText("");
        studentidTextField.setText("");
        gradeTextField.setText("");
        gradeidTextField.setText("");
        feedbackTextField.setText("");
        percentageTextField.setText("");
        locationTextField.setText("");
        methodTextField.setText("");
        responsecodeTextField.setText("");
          ClientApp obj=new ClientApp();
          ClientResponse r=obj.getGradebookdetails();
          String answer =r.toString();
          String [] tokens=answer.split(" ");
          for (String s: tokens)
          {
              System.out.println(s);
          }
          
           String location=tokens[1];
           locationTextField.setText(location);
           responsecodeTextField.setText(tokens[7]);
                 String methodvalue="";
                       for(int i=8; i<tokens.length;i++)
                       {
                           methodvalue=methodvalue+" "+tokens[i]+" ";
                       }
                methodTextField.setText(methodvalue);
        
    }//GEN-LAST:event_gradebookbuttonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ClientUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ClientUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ClientUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ClientUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ClientUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton createRadioButton;
    private javax.swing.JRadioButton deleteRadioButton;
    private javax.swing.JTextField feedbackTextField;
    private javax.swing.JTextField gradeTextField;
    private javax.swing.JButton gradebookbutton;
    private javax.swing.JTextField gradeidTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField locationTextField;
    private javax.swing.JTextField methodTextField;
    private javax.swing.JTextField percentageTextField;
    private javax.swing.JRadioButton putRadioButton;
    private javax.swing.JRadioButton readRadioButton;
    private javax.swing.JTextField responsecodeTextField;
    private javax.swing.JTextField studentidTextField;
    private javax.swing.JTextField studentnameTextField;
    private javax.swing.JButton submitButton;
    // End of variables declaration//GEN-END:variables
}
